version: "{build}"

clone_folder: c:\gopath\src\github.com\itchyny\setupfiles-go

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go env
  - go get -d -v -t ./...

build_script:
  - go version

test_script:
  - go test -v ./...

deploy: false
